server:
  port: 8087

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service
            client-secret:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm