server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecommerce-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader=true
      routes:
        # Routes for API
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
        - id: catalog-service
          uri: http://catalog-service:8082
          predicates:
            - Path=/product/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payment/**
        - id: inventory-service
          uri: http://inventory-service:8085
          predicates:
            - Path=/inventory/**, /warehouse/**
        - id: delivery-service
          uri: http://delivery-service:8086
          predicates:
            - Path=/delivery/**
        - id: auth-service
          uri: http://auth-service:8087
          predicates:
            - Path=/auth/**

        # Routes for Swagger API
        - id: swagger-user-service
          uri: http://user-service:8081
          predicates:
            - Path=/swagger-ui/user/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/user/v3/api-docs, /v3/api-docs
        - id: catalog-service-swagger
          uri: http://catalog-service:8082
          predicates:
            - Path=/swagger-ui/product/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/product/v3/api-docs, /v3/api-docs
        - id: order-service-swagger
          uri: http://order-service:8083
          predicates:
            - Path=/swagger-ui/order/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/order/v3/api-docs, /v3/api-docs
        - id: payment-service-swagger
          uri: http://payment-service:8084
          predicates:
            - Path=/swagger-ui/payment/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/payment/v3/api-docs, /v3/api-docs
        - id: inventory-service-swagger
          uri: http://inventory-service:8085
          predicates:
            - Path=/swagger-ui/inventory/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/inventory/v3/api-docs, /v3/api-docs
        - id: delivery-service-swagger
          uri: http://delivery-service:8086
          predicates:
            - Path=/swagger-ui/delivery/v3/api-docs
          filters:
            - RewritePath=/swagger-ui/delivery/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: User Service
        url: /swagger-ui/user/v3/api-docs
      - name: Catalog Service
        url: /swagger-ui/product/v3/api-docs
      - name: Order Service
        url: /swagger-ui/order/v3/api-docs
      - name: Payment Service
        url: /swagger-ui/payment/v3/api-docs
      - name: Inventory Service
        url: /swagger-ui/inventory/v3/api-docs
      - name: Delivery Service
        url: /swagger-ui/delivery/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true