server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8087/realms/ecommerce-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8087
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
        - id: catalog-service
          uri: http://catalog-service:8082
          predicates:
            - Path=/catalog/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payment/**
        - id: inventory-service
          uri: http://inventory-service:8085
          predicates:
            - Path=/inventory/**
        - id: delivery-service
          uri: http://delivery-service:8086
          predicates:
            - Path=/delivery/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true