server:
  port: 8081

spring:
  application:
    name: user-service
#  config:
#    import: "optional:configserver:http://config-server:8888"

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin_pass

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/