server:
  port: 8083

spring:
  application:
    name: order-service
  #  config:
  #    import: "optional:configserver:http://config-server:8888"

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin_pass

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/